### PR TITLE
Add custom URL support

### PR DESCRIPTION
**Pull request by HelderFSFerreira**
Make the URL redirection possible as it isn't configurable.
#25

### CODE REVIEW

**Comment by HelderFSFerreira** [comment]
Ok, seems fair, working on it.

Just FYI the way to configure the credentials is using environmental variables and that's way I followed this route.
The feature to having the url redirection using the file was implemented so I thought that will be a matter of time to have it implemented using EV ( [issue](https://github.com/boto/boto3/issues/1375) )

**Comment by richvdh** [comment]
Hi @HelderFSFerreira; are you still interested in working on this?

**Comment by HelderFSFerreira** [comment]
Hi,

Yup, sorry for the delay.
I should get it done by the end of this weak. Is it OK for you?

**Comment by richvdh** [comment]
sure, just checking it hadn't been forgotten!

**Comment by richvdh** [comment]
Hi @HelderFSFerreira: I'm going to close this for now. If you find time to work on it in the future we'll be glad to reopen it!

**Pull request closed without merging**
