### PR TITLE
Support intelligent tiering in s3 upload script

### PR DESCRIPTION
**Pull request by rkfg**
Same as #17 but for the upload and cleanup script.

Signed-off-by: Sergey Shpikin \<rkfg@rkfg.me\>

### CODE REVIEW

**Review by anoadragon453 — APPROVED** [review]
Given the context in https://github.com/matrix-org/synapse-s3-storage-provider/pull/17, this looks good to me. CI failure is unrelated to this PR's changes.

**Comment by clokep** [comment]
@anoadragon453 Did you want `master` merged in to fix CI?

**Comment by anoadragon453** [comment]
> @anoadragon453 Did you want `master` merged in to fix CI?

Ah yes, that would be helpful. @rkfg could you do that please? We [recently switched](https://github.com/matrix-org/synapse-s3-storage-provider/pull/53) away from TravisCI after TravisCI ended their support for free tiers.

**Comment by rkfg** [comment]
Looks like we're good!

**Comment by anoadragon453** [comment]
@rkfg Thanks for doing that so quickly!

**Review by michaelkaye — COMMENTED** [review]
Sounds fine by me

**Pull request merged**
